Improve gitpod deployment
couchbase-examples/python-quickstart pull request #2
Opened 2021-07-06 12:12 UTC by nithishr

- Messaging to indicate the app initializing / loading
- Add a splash screen that redirects to the swagger documentation once the health check is stable
- Add a preview to gitpod config

2021-07-07 14:34 UTC, deniswsrosa requested changes
I run the app 4 times, and it worked just once. So we still need to put some effort to find out why the app is failing.

2021-07-07 14:34 UTC, deniswsrosa commented on src/app.py
> +            time.sleep(6)
Do not sleep before letting the user know that you are waiting for something to happen

2021-07-07 14:34 UTC, deniswsrosa commented on src/app.py
> +        )
Giving the fact that we are running inside gitpod, refreshing the page will essentially refresh the whole environment, wich is not what we want here

2021-07-19 17:02 UTC, chedim approved these changes

2021-07-20 07:59 UTC, merged